export default {
  ADD_TICKET_REQUEST: "ADD_TICKET_REQUEST",
  ADD_TICKET_SUCCESS: "ADD_TICKET_SUCCESS",
  ADD_TICKET_FAILURE: "ADD_TICKET_FAILURE",

  GET_TICKETS_REQUEST: "GET_TICKETS_REQUEST",
  GET_TICKETS_SUCCESS: "GET_TICKETS_SUCCES",
  GET_TICKETS_FAILURE: "GET_TICKETS_FAILURE",

  GET_TICKETS_BY_USER_REQUEST: "GET_TICKETS_BY_USER_REQUEST",
  GET_TICKETS_BY_USER_SUCCESS: "GET_TICKETS_BY_USER_SUCCES",
  GET_TICKETS_BY_USER_FAILURE: "GET_TICKETS_BY_USER_FAILURE",

  UPDATE_TICKET_REQUEST: "UPDATE_TICKET_REQUEST",
  UPDATE_TICKET_SUCCESS: "UPDATE_TICKET_SUCCES",
  UPDATE_TICKET_FAILURE: "UPDATE_TICKET_FAILURE",

  DELETE_TICKET_REQUEST: "DELETE_TICKET_REQUEST",
  DELETE_TICKET_SUCCESS: "DELETE_TICKET_SUCCES",
  DELETE_TICKET_FAILURE: "DELETE_TICKET_FAILURE",

  RESET_TICKET: "RESET_TICKET",
};
