export const userConstants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    USER_LOGOUT: "USER_LOGOUT",

    USERS_GETALL_REQUEST: "USERS_GETALL_REQUEST",
    USERS_GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
    USERS_GETALL_FAILURE: "USERS_GETALL_FAILURE",

    USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    USER_DELETE_FAILURE: "USER_DELETE_FAILURE",
};
